services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WDB\BeThemeLegacy\EventListener\BeforeStylesheetsRenderingEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'be-theme-legacy/before-stylesheets-rendering-event'
        event: TYPO3\CMS\Core\Page\Event\BeforeStylesheetsRenderingEvent
        method: '__invoke'
        public: true

  WDB\BeThemeLegacy\EventListener\BeforeJavaScriptsRenderingEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'be-theme-legacy/before-javascript-rendering-event'
        event: TYPO3\CMS\Core\Page\Event\BeforeJavaScriptsRenderingEvent
        method: '__invoke'
        public: true
